/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ChatGPT_Chatbot;

import java.io.IOException;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() throws IOException, InterruptedException {
        App classUnderTest = new App();
    }
}
